version: "3.9"

services:
  web:
    build:
      context: .
    volumes:
      - .:/opt
      - "build:/opt/_build"
      - "deps:/opt/deps"
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev

    networks:
      default:
        aliases:
          - currency_converter_web
 
  test:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/opt
      - "build:/opt/_build"
      - "deps:/opt/deps"
    command: mix do deps.get --only, coveralls --trace --color, format --check-formatted, credo --strict
    environment:
      - MIX_ENV=test

volumes:
  build:
  deps:

networks:
  default:
    external:
      name: currency_converter