openapi: "3.0.2"
info:
  title: ExChange API
  description: An API to convert amounts between pairs of currencies
  version: "1.0"
servers:
  - url: http://localhost:4000/api/
paths:
  /convert/{amount}/{current}/{target}:
    get:
      summary: Converts the given amount from current to target currency
      description: Returns the amount converted to the target currency, and the time the exchange rate was updated
      parameters:
        - in: path
          name: amount
          description: Amount being converted
          schema:
            type: string
          required: true
        - in: path
          name: current
          description: Symbol of the currency being converted
          schema:
            type: string
          required: true
        - in: path
          name: target
          description: Symbol of the target currency
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Conversion response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Conversion"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string

        "500":
          description: Internal Server Error

components:
  schemas:
    Conversion:
      type: object
      required:
        - conversion_info
      properties:
        data:
          type: object
          properties:
            amount:
              type: number
              format: double
              minimum: 0
              description: The converted amount at target currency
            currency:
              type: string
              description: Target currency the amount was converted to
            updated_at:
              type: string
              description: Timestamp for last update on the exchange rate on UTC timezone
